title: Ed Baker
description: Interdisciplinary researcher using sensor networks and acoustics to monitor biodiversity and environments.
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
url: "https://ebaker.me.uk"

author: Ed Baker

social:
  name: Ed Baker
  links:
    - https://github.com/edwbaker
    - https://orcid.org/0000-0002-5887-9543
    - https://linktr.ee/edwbaker
